### ISSUE TITLE
Problem in accessing kibana 

### ISSUE THREAD

**Issue by Bowrna** [sergiokhayyat/SocialFearGreedIndex#1]
Hi,

I tried to create this service and run it in my machine. But couldn't access kibana from my machine. 
When i searched kibana logs i found it couldn't connect with ES. On checking ES logs, found VM allocated is not enough. 
![maxvm](https://user-images.githubusercontent.com/10162465/27271196-f0d29b14-54e0-11e7-8957-909c6de980dd.png)

![serviceps](https://user-images.githubusercontent.com/10162465/27252042-ef3f08fc-5371-11e7-8789-a4764916220a.png)
![kibanalogs](https://user-images.githubusercontent.com/10162465/27271157-afcc2860-54e0-11e7-9cdd-abda083ed767.png)

**Comment by sergiokhayyat** [comment]
Its a host configuration problem. You have to set the `vm.max_map_count` kernel parameter to, at least, 262144 (see https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)
